server:
  port: 8082

spring:
  application:
    name: payment-service

  rabbitmq:
    host: localhost
    port: 5672

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: password

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/postgres
    user: admin
    password: password
    schemas: payment_schema
    create-schemas: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        # Create a specific schema for this microservice
        default_schema: payment_schema
    # Show SQL in the console so you can see it working
    show-sql: true